const NOMES = [
  "jacaré anônimo",
  "tamanduá anônimo",
  "tatu anônimo",
  "axolote anônimo",
  "texugo anônimo",
  "morcego anônimo",
  "urso anônimo",
  "castor anônimo",
  "peixe anônimo",
  "búfalo anônimo",
  "camelo anônimo",
  "camaleão anônimo",
  "chita anônima",
  "esquilo anônimo",
  "chinchila anônima",
  "chupacabra anônimo",
  "cormorão anônimo",
  "coiote anônimo",
  "corvo anônimo",
  "dingo anônimo",
  "dinossauro anônimo",
  "cão anônimo",
  "golfinho anônimo",
  "dragão anônimo",
  "pato anônimo",
  "polvo anônimo",
  "elefante anônimo",
  "furão anônimo",
  "raposa anônima",
  "rã anônima",
  "girafa anônima",
  "ganso anônimo",
  "urso-pardo anônimo",
  "hamster anônimo",
  "porco-espinho anônimo",
  "hipopótamo anônimo",
  "hiena anônima",
  "chacal anônimo",
  "jackalope anônimo",
  "iguana anônima",
  "canguru anônimo",
  "kiwi anônimo",
  "coala anônimo",
  "kraken anônimo",
  "lêmure anônimo",
  "leopardo anônimo",
  "ligre anônimo",
  "leão anônimo",
  "lhama anônima",
  "peixe-boi anônimo",
  "macaco anônimo",
  "alce anônimo",
  "nyan cat anônimo",
  "orangotango anônimo",
  "lontra anônima",
  "panda anônimo",
  "pinguim anônimo",
  "ornitorrinco anônimo",
  "abóbora anônima",
  "coelho anônimo",
  "guaxinim anônimo",
  "rinoceronte anônimo",
  "ovelha anônima",
  "gambá anônimo",
  "esquilo anônimo",
  "tigre anônimo",
  "tartaruga anônima",
  "unicórnio anônimo",
  "morsa anônima",
  "lobo anônimo",
  "carcaju anônimo",
  "vombate anônimo",
];
export const obterNomeAleatorio = () => {
  const indiceAletorio = Math.floor(Math.random() * NOMES.length);
  const nomeAleatorio = NOMES[indiceAletorio];
  const nomeTratado = nomeAleatorio[0].toUpperCase() + nomeAleatorio.slice(1);
  return nomeTratado;
}